version: 0.0
os: linux
files:
  - source: /
    destination: /projects/test
hooks:
  BeforeInstall:
    - location: scripts/blog/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/blog/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
