version: 0.0
os: linux
files:
  - source: /
    destination: /home/server/projects/blog-andrewgingrich
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
